version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: php-apache-1
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
      - ./src/php02:/usr/local/apache2/htdocs/php02
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - type: bind
        source: /home/honey/coachtech/php/src
        target: /var/www/html
        bind:
          create_host_path: true
      - type: bind
        source: /home/honey/coachtech/php/src/php02
        target: /var/www/html/php02
        bind:
          create_host_path: true



